//
//  Teams.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.12
//

import Foundation
import UIKit
import AWSDynamoDB

class Teams: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _teams: String?
    
    class func dynamoDBTableName() -> String {

        return "jogarun-mobilehub-2062646821-teams"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_teams" : "teams",
        ]
    }
}
